language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

services:
    - redis-server

before_script:
    - composer install --no-interaction

script:
    - vendor/bin/phpunit -c phpunit-laravel-52.xml
    - vendor/bin/phpunit -c phpunit-laravel-53.xml
    - vendor/bin/phpunit -c phpunit-laravel-54.xml
    - vendor/bin/phpunit -c phpunit-laravel-55.xml
    - vendor/bin/phpunit -c phpunit-laravel-56.xml
    - vendor/bin/phpunit -c phpunit-laravel-57.xml
    - vendor/bin/phpunit -c phpunit-laravel-58.xml
    - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then vendor/bin/phpunit -c phpunit-laravel-6.xml --coverage-clover build/logs/clover.xml; fi

after_success:
    - travis_retry php vendor/bin/php-coveralls  -v
